# See:
# https://docs.docker.com/compose/gettingstarted/
services:
  web:
    build: .
    command: mkdocs serve
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/usr/src/app:cached
    environment:
      PYTHONPATH: .
