# See:
# https://docs.docker.com/compose/gettingstarted/
services:
  web:
    build: .
    command: sleep infinity
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/usr/src/app:cached
      - uv-cache:/workspace/.cache/uv
    environment:
      PYTHONPATH: .
      UV_CACHE_DIR: /workspace/.cache/uv

volumes:
  uv-cache:
    driver: local
