name: Check Markdown links for modified files

on: [ pull_request ]

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Get changed markdown files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            docs/**/*.md
            README.md
            CONTRIBUTING.md

      - name: Restore lychee cache
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.ref }}
          restore-keys: cache-lychee-

      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          args: --cache --max-cache-age 14d --quiet ${{
            steps.changed-files.outputs.all_changed_files }}
          fail: true
