name: Check Markdown links with scheduled job

on:
  schedule:
  # Run everyday at 12:30 AM, JST (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
  - cron: "30 15 * * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
